name: flutter_tdd_template
description: A new Flutter Test-driven development template

version: 0.0.1+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Localization dependency
  intl: ^0.17.0
  # State management
  flutter_bloc: ^7.0.0
  # Service Locator
  get_it: ^6.0.0
  # Functional programming in Dart
  dartz: ^0.10.0-nullsafety.1
  # shared preferences
  shared_preferences: ^2.0.5
  #  Http client for Dart
  dio: ^4.0.0
  # compare objects
  equatable: ^2.0.0
  # adapting screen and font size
  flutter_screenutil: ^5.0.0
  # scroll component drop-down refresh
  pull_to_refresh: ^1.6.4
  # launching a URL in the mobile platform. Supports iOS and Android.
  url_launcher: ^6.0.3
  # text animations
  animated_text_kit: ^4.1.1
  #  A simple widget wrapper to enable modal progress HUD
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  # This Flutter plugin provides an API for querying information about an application package.
  package_info: ^2.0.0
  # A pure dart toast Library.
  oktoast: ^3.0.0
  curved_navigation_bar: ^0.4.0-nullsafety.0


  cupertino_icons: ^1.0.2


dev_dependencies:
  build_runner: ^1.12.2
  json_serializable: ^4.1.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/png/
    - assets/png/error/
    - assets/png/menu/


flutter_intl:
  main_locale: en_US
  enabled: true